config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root "palettes#new"
  get "about" => "homes#about"
  get "terms_of_use" => "homes#terms"
  get "privacy_policy" => "homes#policy"

  resources :users, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :palettes, only: [:index, :new, :create, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  resources :palette_seconds, only: [:index, :new, :create, :show, :destroy] do
    resources :like_seconds, only: [:create, :destroy]
  end

  namespace :mypage do
    resource :profile, only: [:edit, :show, :update]
    get 'palettes' => 'colors#palettes'
    get 'palette_seconds' => 'color_seconds#palette_seconds'
    get "palettes/likes" => "colors#likes"
    get "palette_seconds/likes" => "color_seconds#likes"
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  namespace :admin do
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'

    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :colors, only: [:index, :show, :edit, :update, :destroy]
    resources :color_seconds, only: [:index, :show, :edit, :update, :destroy]
  end

  post '/guest_login', to: 'user_sessions#guest_login'
end

app/controllers/mypage/color_seconds_controller.rb
class Mypage::ColorSecondsController < ApplicationController
  layout 'layouts/colorless'

  def palette_seconds
    @palette_seconds = current_user.palette_seconds.order(created_at: :desc).page(params[:page])
  end

  def likes
    @palette_seconds = current_user.like_seconds_palette_seconds.includes([:like_seconds, :tag_seconds]).order(created_at: :desc).includes([:user, :like_seconds]).page(params[:page])
  end
end

app/controllers/mypage/colors_controller.rb
class Mypage::ColorsController < ApplicationController
  layout 'layouts/colorless'

  def palettes
    @palettes = current_user.palettes.order(created_at: :desc).includes(:tags).page(params[:page])
  end

  def likes
    @palettes = current_user.likes_palettes.includes([:likes, :tags]).page(params[:page])
  end
end

app/controllers/mypage/profiles_controller.rb
class Mypage::ProfilesController < ApplicationController
  layout 'layouts/colorless'
  before_action :set_user, only: [:show, :edit, :update]

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = '編集に成功しました'
      redirect_to mypage_profile_path
    else
      flash.now[:danger] = '編集に失敗しました'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(current_user.id)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      flash[:success] =  '編集しました'
      redirect_back fallback_location:root_path
    else
      flash.now[:danger] = '編集に失敗しました'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

app/views/mypage/profiles/edit.html.erb
<% set_meta_tags title: 'Profile' %>
<div class="md:w-3/4 my-5 mx-auto">

  <div class="my-5">
    <div class="mx-auto w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
            ユーザー情報編集
        </h1>
        <%= form_with model: @user, url: mypage_profile_path, local: true do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="my-7">
            <%= f.label :name, "名前" %>
            <%= f.text_field :name, class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', placeholder:"name@company.com" %>
          </div>
          <div class="my-7">
            <%= f.label :email, "メールアドレス" %>
            <%= f.text_field :email, class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', placeholder:"name@company.com" %>
          </div>
          <div class="my-7">
            <button class="w-full text-white bg-green-400 hover:bg-green-300  font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
              <%= f.submit '更新', class:"bg-transparent" %>
            </button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/mypage/profiles/show.html.erb
<% set_meta_tags title: 'Profile' %>
<div class="md:w-3/4 my-5 mx-auto">

  <div class="my-5">
    <div class="mx-auto w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white text-center">
          ユーザー情報
        </h1>
          <div class="my-7">
            <div class="my-2">
              登録日
            </div>
            <div>
              <%= l @user.created_at %>
            </div>
          </div>
          <div class="my-7">
            <div class="my-2">
              名前
            </div>
            <div>
              <%= @user.name %>
            </div>
          </div>
          <div class="my-7">
            <div class="my-2">
              メールアドレス
            </div>
            <div>
              <%= @user.email %>
            </div>
          </div>
          <div class="my-7">
            <button class="w-full">
              <%= link_to '編集', edit_mypage_profile_path, class:" text-white bg-green-400 hover:bg-green-300  font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" %>
            </button>
          </div>
      </div>
    </div>
  </div>
</div>