config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root "palettes#new"
  get "about" => "homes#about"
  get "terms_of_use" => "homes#terms"
  get "privacy_policy" => "homes#policy"

  resources :users, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :palettes, only: [:index, :new, :create, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  resources :palette_seconds, only: [:index, :new, :create, :show, :destroy] do
    resources :like_seconds, only: [:create, :destroy]
  end

  namespace :mypage do
    resource :profile, only: [:edit, :show, :update]
    get 'palettes' => 'colors#palettes'
    get 'palette_seconds' => 'color_seconds#palette_seconds'
    get "palettes/likes" => "colors#likes"
    get "palette_seconds/likes" => "color_seconds#likes"
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  namespace :admin do
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'

    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :colors, only: [:index, :show, :edit, :update, :destroy]
    resources :color_seconds, only: [:index, :show, :edit, :update, :destroy]
  end

  post '/guest_login', to: 'user_sessions#guest_login'
end

app/views/shared/_active_palette.html.erb
<div class="flex my-5">
  <% if %w[new_palette new_palette_second root].any? {|name| current_page?(send("#{name}_path"))} %>
    <div class="text-center w-1/2">
      <%= link_to "Web Site Look", new_palette_path, class: "p-1 block #{active_if('palettes')}", data: {"turbolinks" => false} %>
    </div>
    <div class="text-center w-1/2">
      <%= link_to "Web App Look", new_palette_second_path, class: "p-1 block #{active_if('palette_seconds')}", data: {"turbolinks" => false} %>
    </div>
  <% elsif %w[palettes palette_seconds].any? {|name| current_page?(send("#{name}_path"))} %>
    <div class="text-center w-1/2">
      <%= link_to "Web Site Look", palettes_path, class: "p-1 block #{active_if('palettes')}", data: {"turbolinks" => false} %>
    </div>
    <div class="text-center w-1/2">
      <%= link_to "Web App Look", palette_seconds_path, class: "p-1 block #{active_if('palette_seconds')}", data: {"turbolinks" => false} %>
    </div>
  <% elsif %w[mypage_palettes_likes mypage_palette_seconds_likes].any? {|name| current_page?(send("#{name}_path"))} %>
    <div class="text-center w-1/2">
      <%= link_to "Web Site Look", mypage_palettes_likes_path, class: "p-1 block #{active_if('mypage/colors')}", data: {"turbolinks" => false} %>
    </div>
    <div class="text-center w-1/2">
      <%= link_to "Web App Look", mypage_palette_seconds_likes_path, class: "p-1 block #{active_if('mypage/color_seconds')}", data: {"turbolinks" => false} %>
    </div>
  <% elsif %w[admin_colors admin_color_seconds].any? {|name| current_page?(send("#{name}_path"))} %>
    <div class="text-center w-1/2">
      <%= link_to "Web Site Look", admin_colors_path, class: "p-1 block #{active_if('admin/colors')}", data: {"turbolinks" => false} %>
    </div>
    <div class="text-center w-1/2">
      <%= link_to "Web App Look", admin_color_seconds_path, class: "p-1 block #{active_if('admin/color_seconds')}", data: {"turbolinks" => false} %>
    </div>
  <% end %>
</div>

app/views/shared/_before_login_header.html.erb
<nav class="flex items-center justify-between flex-wrap bg-yellow-300 p-6">
  <div class="flex items-center flex-shrink-0 text-white">
    <span class="font-semibold text-xl tracking-tight">
      <%= link_to 'MyPalette', root_path, data: {"turbolinks" => false} %>
    </span>
  </div>

  <div class="hidden md:visible block flex md:flex lg:items-center lg:w-auto mr-1">
    <div class="mr-1">
      <%= link_to 'ゲストログイン', guest_login_path, method: :post, class:"mt-0 mx-1 inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-yellow-500 hover:bg-white", data: {"turbolinks" => false}  %>
    </div>
    <div class="mr-1">
      <%= link_to '使い方', about_path, class:"mt-0 mx-1 inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-yellow-500 hover:bg-white", data: {"turbolinks" => false}  %>
    </div>
    <div class="mr-2">
      <%= link_to 'All Colors', palettes_path, class:"mt-0 mx-1 inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-yellow-500 hover:bg-white", data: {"turbolinks" => false}  %>
    </div>
    <div class="mr-2">
      <%= link_to 'Register', new_user_path, class:"mt-0 inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-yellow-500 hover:bg-white"  %>
    </div>
    <div>
      <%= link_to 'Login', login_path, class:"mt-0 inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-yellow-500 hover:bg-white"  %>
    </div>
  </div>
</nav>

app/views/shared/_button2.html.erb
<div class =" w-full">
  <% if %w[admin_color_seconds].any? {|name| current_page?(send("#{name}_path"))} %>
    <button class="text-white my-2 w-12">
      <%= link_to "編集", edit_admin_color_second_path(palette_second), class:"bg-green-400 hover:bg-green-300 px-2 py-2 rounded", data: {"turbolinks" => false} %>
    </button>
    <button class="text-white my-2 w-12">
      <%= link_to "削除", admin_color_second_path(palette_second), class:"bg-red-500 hover:bg-red-400 px-2 py-2 rounded", method: :delete, data: { confirm: "削除してもよろしいですか？" } %>
    </button>
  <% elsif %w[palette_seconds mypage_palette_seconds mypage_palette_seconds_likes].any? {|name| current_page?(send("#{name}_path"))} %>
    <%= render 'shared/unlike_detail_button2', palette_second: palette_second %>
  <% elsif current_user.own?(palette_second) %>
    <button class="text-white my-2 w-12">
      <%= link_to '削除', palette_second_path(palette_second),class:"bg-red-500 hover:bg-red-400 px-2 py-2 rounded", method: :delete, data: { confirm: "削除してもよろしいですか" } %>
    </button>
  <% else %>
    <%= render 'shared/like_button2', palette_second: palette_second %>
  <% end %>
</div>

app/views/shared/_color_sample.html.erb
<div class="text-center my-2">
  <span class="arrow-down"><i class="fa-solid fa-circle-arrow-down"></i></span>
</div>

<header class="body-change-bg bg-white border-t flex items-center justify-between flex-wrap p-6">

  <div class="flex items-center flex-shrink-0">
    <span class="main-change font-semibold text-xl tracking-tight">SampleApp</span>
  </div>

  <div class="hidden md:visible block flex md:flex lg:items-center lg:w-auto mr-1">
    <div>
      <a class="mt-0 inline-block text-sm px-4 py-2 ">About</a>
      <a class="mt-0 inline-block text-sm px-4 py-2 ">Products</a>
      <a class="mt-0 inline-block text-sm px-4 py-2 ">News</a>
      <a class="main-change-bg bg-gray-300 mt-0 inline-block text-sm px-4 py-2 rounded-full">Contact</a>
    </div>
  </div>

</header>


<main class="">

  <div class="main-container parent">
    <div id="bg-change-id" class="img-bg-black">
      <div class="body-change-bg bg-white child p-4 text-center">
        <h2 class=" text-3xl font-bold">Lorem Ipsum</h2>
        <p class="py-2">Lorem Ipsum is simply dummied text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
        <button class="sub-change-bg bg-gray-300 text-md px-5 py-1 my-2 rounded-full text-center text-black">Read more</button>
      </div>
    </div>
  </div>

  <div class="body-change-bg px-10 py-10">
    <div class="sm:flex py-6">
      <div class="parent1 md:w-3/6 my-auto mx-auto">
        <div class="child-img">
          <%= image_tag 'room.jpg' %>
        </div>
        <div class="main-change-bg child1 bg-white"></div>
      </div>
      <div class="m-10 md:w-3/6">
        <h2 class="main-change text-2xl lg:text-3xl font-bold my-2">About us</h2>
        <h2 class="text-3xl lg:text-5xl font-bold lg:py-8">Your App looks fancy like these color combination.</h2>
        <p class="py-2">Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        <p class="py-2">Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        <div class="py-2">
          <button class="sub-change-bg text-md px-5 py-1 my-2 bg-gray-300 rounded-full text-center">Read more</button>
        </div>
      </div>
    </div>
  </div>

  <div class="main-change-bg bg-gray-300 px-5 py-10">
    <div class="text-center">
      <h2 class="text-2xl font-bold">Products</h2>
      <p class="py-2">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
    </div>
    <div class="sm:flex  py-6">
      <div class="p-6 m-6 bg-white">
        <%= image_tag 'undraw_By_my_car_re_eyri.png' %>
        <h2 class="text-center text-xl font-bold my-2">Products</h2>
        <p class="text-black">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
        <div class="text-center">
          <button class="sub-change-bg text-md px-5 py-1 my-2 bg-gray-300 rounded-full text-center">Read more</button>
        </div>
      </div>
      <div class="p-6 m-6 bg-white">
        <%= image_tag 'undraw_By_my_car_re_eyri.png' %>
        <h2 class="text-center text-xl font-bold my-2">Products</h2>
        <p class="text-black">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
        <div class="text-center">
          <button class="sub-change-bg text-md px-5 py-1 my-2 bg-gray-300 rounded-full text-center">Read more</button>
        </div>
      </div>
      <div class="p-6 m-6 bg-white">
        <%= image_tag 'undraw_By_my_car_re_eyri.png' %>
        <h2 class="text-center text-xl font-bold my-2">Products</h2>
        <p class="text-black">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
        <div class="text-center">
          <button class="sub-change-bg text-md px-5 py-1 my-2 bg-gray-300 rounded-full text-center">Read more</button>
        </div>
      </div>
    </div>
  </div>

  <div class="body-change-bg bg-white lg:px-40 py-10">
    <div class="text-center">
      <h2 class="main-change text-2xl font-bold">News</h2>
      <p class="py-2">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
    </div>
    <div class="p-6 text-center">
      <div class="">
        <ul>
          <li class="py-3 my-3 border-b">
            <span>2023.01.01</span>
            <span class="main-change-bg bg-gray-300 p-1 rounded mx-3">product</span>
            <span>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</span>
          </li>
          <li class="py-3 my-3 border-b">
            <span>2023.01.01</span>
            <span class="main-change-bg bg-gray-300 p-1 rounded mx-3">product</span>
            <span>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</span>
          </li>
          <li class="py-3 my-3 border-b">
            <span>2023.01.01</span>
            <span class="main-change-bg bg-gray-300 p-1 rounded mx-3">product</span>
            <span>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</span>
          </li>
        </ul>
      </div>
        <div class="text-center">
          <button class="sub-change-bg bg-gray-300 text-md px-5 py-1 my-2 rounded-full text-center">Read more</button>
        </div>
    </div>
  </div>

</main>


<footer class="main-change-bg bg-gray-300 px-10 py-10 border-b">
  <div class="grid md:grid-cols-3 grid-cols-1">

    <div class="text-center">
      <div class="font-bold py-2 lg:text-xl">SampleApp</div>
      <div class="text-xs">© 2022 SampleApp</div>
    </div>

    <div class="no_display">
      <div>
        <a class="mt-0 inline-block text-sm px-4 py-2 ">About</a>
      </div>
      <div>
        <a class="mt-0 inline-block text-sm px-4 py-2 ">Products</a>
      </div>
      <div>
        <a class="mt-0 inline-block text-sm px-4 py-2 ">News</a>
      </div>
    </div>

    <div class="no_display">
      <button class="sub-change-bg bg-white mt-0 inline-block text-xl lg:px-10 px-6 py-2 rounded-full">Contact</button>
    </div>

  </div>
</footer>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="text-red-700 bg-red-100 rounded-lg p-4 my-4">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'success' %>
    <div class="text-green-700 bg-green-100 rounded-lg p-4"><%= message %></div>
  <% elsif message_type == 'danger' %>
    <div class="text-red-700 bg-red-100 rounded-lg p-4"><%= message %></div>
  <% elsif message_type == 'warning' %>
    <div class="text-yellow-700 bg-yellow-100 rounded-lg p-4"><%= message %></div>
  <% else %>
    <div class="text-blue-700 bg-blue-100 rounded-lg p-4"><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<nav class="flex items-center justify-between flex-wrap bg-yellow-300 p-6">
  <div class="flex items-center flex-shrink-0 text-white">
    <span class="font-semibold text-xl tracking-tight">
      <%= link_to 'MyPalette', root_path, data: {"turbolinks" => false} %>
    </span>
  </div>

  <div class="hidden md:visible block flex md:flex lg:items-center lg:w-auto mr-1">
    <% if current_user.admin? %>
      <div>
        <%= link_to 'Admin Menu', admin_colors_path, class:"mt-0 mx-1 inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-yellow-500 hover:bg-white", data: {"turbolinks" => false}  %>
      </div>
    <% else %>
     <div>
        <%= link_to 'All Colors', palettes_path, class:"mt-0 mx-1 inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-yellow-500 hover:bg-white", data: {"turbolinks" => false}  %>
      </div>
    <% end %>
    <div>
      <%= link_to 'スキ Colors', mypage_palettes_likes_path, class:"mt-0 mx-1 inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-yellow-500 hover:bg-white", data: {"turbolinks" => false}  %>
    </div>
    <div>
      <%= link_to 'My Colors', mypage_palettes_path, class:"mt-0 mx-1 inline-block px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-yellow-500 hover:bg-white", data: {"turbolinks" => false}  %>
    </div>

    <div class=" leading-none border rounded text-white border-white hover:border-transparent hover:text-yellow-500 hover:bg-white">
      <button class="drop-btn mt-0 mx-1 inline-block text-xs px-4 py-2" id="dropbtn">
        <i class="fa-regular fa-user" id="droparrow"></i>
      </button>
      <div class="dropdown" id="dropdown">
        <%= link_to 'Profile', mypage_profile_path, class:"inline-block px-3 py-2 leading-none border rounded text-white border-gray-200 hover:border-transparent hover:text-white hover:bg-yellow-500", data: {"turbolinks" => false}  %>
        <%= link_to 'ログアウト', logout_path, method: :delete, class:"inline-block px-3 py-2 leading-none border rounded text-white border-gray-200 hover:border-transparent hover:text-white hover:bg-yellow-500" %>
      </div>
    </div>

  </div>
</nav>

app/views/shared/_like_button.html.erb
<% if current_user.like?(palette) %>
  <button class="px-3 py-2">
    <%= link_to palette_like_path(palette_id: palette.id, id: current_user.likes.find_by(palette_id: palette.id)), method: :delete do %>
      <i class="fa-solid fa-heart red-heart"></i>
    <% end %>
  </button>
<% else %>
  <button class="px-3 py-2">
    <%= link_to palette_likes_path(palette), method: :post do %>
      <i class="fa-regular fa-heart"></i>
    <% end %>
  </button>
<% end %>

app/views/shared/_like_button2.html.erb
<% if current_user.like_second?(palette_second) %>
  <button class="px-3 py-2">
    <%= link_to palette_second_like_second_path(palette_second_id: palette_second.id, id: current_user.like_seconds.find_by(palette_second_id: palette_second.id)), method: :delete do %>
      <i class="fa-solid fa-heart red-heart"></i>
    <% end %>
  </button>
<% else %>
  <button class="px-3 py-2">
    <%= link_to palette_second_like_seconds_path(palette_second), method: :post do %>
      <i class="fa-regular fa-heart"></i>
    <% end %>
  </button>
<% end %>

app/views/shared/_unablecolor.html.erb
<div class="sm:flex justify-center mt-5 mx-auto">

  <div class="border border-b-2 m-1 p-4 bg-gray-50 hover:bg-white">
    <div class="flex ">
      <div class="px-3 my-auto w-4/6">
        Main Color
      </div>
      <div class="my-auto">
        <input type="color" class="main-color colorinput my-auto" value=<%= palette.main %> %>
      </div>
    </div>
    <div class="text-center">
      <%= palette.main %>
    </div>
  </div>

  <div class="border border-b-2 m-1 p-4 bg-gray-50 hover:bg-white">
    <div class="flex ">
      <div class="px-3 my-auto w-4/6">
        Sub Color
      </div>
      <div class="my-auto">
        <input type="color" class="sub-color colorinput my-auto" value=<%= palette.sub %> %>
      </div>
    </div>
    <div class="text-center">
      <%= palette.sub %>
    </div>
  </div>

  <div class="border border-b-2 m-1 p-4 bg-gray-50 hover:bg-white">
    <div class="flex ">
      <div class="px-3 my-auto w-4/6">
        Body Color
      </div>
      <div class="my-auto">
        <input type="color" class="body-color colorinput my-auto" value=<%= palette.body %> %>
      </div>
    </div>
    <div class="text-center">
      <%= palette.body %>
    </div>
  </div>

  <div class="border border-b-2 m-1 p-4 bg-gray-50 hover:bg-white">
    <div class="flex ">
      <div class="px-3 my-auto w-4/6">
        Bg Image
      </div>
      <div class="my-auto">
        <input class="bgimage-change bg-input-n my-auto" value=<%= palette.bgimage %> disabled='true'>
      </div>
    </div>
    <div class="text-center mt-1">
      <%= palette.bgimage %>
    </div>
  </div>

  <div class="text-center my-auto m-1">
    <%= render partial: 'shared/button', locals: { palette: palette} %>
  </div>

</div>

<div class="text-center my-3">
  <% palette.tags.each do |tag| %>
    <span class="text-center px-1 mx-1 bg-gray-100 border text-gray-500 rounded-lg hover:text-black">
      <%= link_to tag.name, palettes_path(tag_name: tag.name), data: { turbolinks: false } %>
    </span>
  <% end %>
</div>


<%= javascript_pack_tag 'color/unablecolor_change' %>

app/views/shared/_unablecolor2.html.erb
<div class="sm:flex justify-center mt-5 mx-auto">

  <div class="border border-b-2 m-1 p-4 bg-gray-50 hover:bg-white">
    <div class="flex ">
      <div class="px-3 my-auto w-4/6">
        Main Color
      </div>
      <div class="my-auto">
        <input type="color" class="main-color colorinput my-auto" value=<%= palette_second.main %>  %>
      </div>
    </div>
    <div class="text-center">
      <%= palette_second.main %>
    </div>
  </div>

  <div class="border border-b-2 m-1 p-4 bg-gray-50 hover:bg-white">
    <div class="flex ">
      <div class="px-3 my-auto w-4/6">
        Sub Color
      </div>
      <div class="my-auto">
        <input type="color" class="sub-color colorinput my-auto" value=<%= palette_second.sub %>  %>
      </div>
    </div>
    <div class="text-center">
      <%= palette_second.sub %>
    </div>
  </div>

  <div class="border border-b-2 m-1 p-4 bg-gray-50 hover:bg-white">
    <div class="flex ">
      <div class="px-3 my-auto w-4/6">
        Body Color
      </div>
      <div class="my-auto">
        <input type="color" class="body-color colorinput my-auto" value=<%= palette_second.body %>  %>
      </div>
    </div>
    <div class="text-center">
      <%= palette_second.body %>
    </div>
  </div>

  <div class="border border-b-2 m-1 p-4 bg-gray-50 hover:bg-white">
    <div class="flex ">
      <div class="px-3 my-auto w-4/6">
        Bg Color
      </div>
      <div class="my-auto">
        <input type="color" class="bg-color colorinput my-auto" value=<%= palette_second.bg %>  %>
      </div>
    </div>
    <div class="text-center">
      <%= palette_second.bg %>
    </div>
  </div>

  <div class="text-center my-auto m-1">
    <%= render partial: 'shared/button2', locals: { palette_second: palette_second} %>
  </div>

</div>

<div class="text-center my-3">
  <% palette_second.tag_seconds.each do |tag| %>
    <span class="text-center px-1 mx-1 bg-gray-100 border text-gray-500 rounded-lg hover:text-black">
      <%= link_to tag.name, palette_seconds_path(tag_second_name: tag.name), data: { turbolinks: false } %>
    </span>
  <% end %>
</div>

<%= javascript_pack_tag 'color/unablecolor_change' %>

app/views/shared/_unlike_detail_button.html.erb
<% if current_user&.own?(palette) %>
  <button class="text-white my-2 w-12">
    <%= link_to '詳細', palette_path(palette), class:"bg-green-400 hover:bg-green-300 px-2 py-2 rounded", data: {"turbolinks" => false} %>
  </button>
  <button class="text-white my-2 w-12">
    <%= link_to '削除', palette_path(palette), class:"bg-red-500 hover:bg-red-400 px-2 py-2 rounded", method: :delete, data: { confirm: "削除してもよろしいですか" } %>
  </button>
<% elsif current_user&.like?(palette) %>
  <button class="text-white my-2 w-12">
    <%= link_to '詳細', palette_path(palette), class:"bg-green-400 hover:bg-green-300 px-2 py-2 rounded", data: {"turbolinks" => false} %>
  </button>
  <button class="px-3 py-2">
    <%= link_to palette_like_path(palette_id: palette.id, id: palette.likes.find { |b| b.user_id == current_user.id }), method: :delete do %>
      <i class="fa-solid fa-heart red-heart"></i>
    <% end %>
  </button>
<% else %>
  <button class="text-white my-2 w-12">
    <%= link_to '詳細', palette_path(palette), class:"bg-green-400 hover:bg-green-300 px-2 py-2 rounded", data: {"turbolinks" => false} %>
  </button>
  <button class="px-3 py-2">
    <%= link_to palette_likes_path(palette), method: :post do %>
      <i class="fa-regular fa-heart"></i>
    <% end %>
  </button>
<% end %>

app/views/shared/_unlike_detail_button2.html.erb
<% if current_user&.own?(palette_second) %>
  <button class="text-white my-2 w-12">
    <%= link_to '詳細', palette_second_path(palette_second), class:"bg-green-400 hover:bg-green-300 px-2 py-2 rounded", data: {"turbolinks" => false} %>
  </button>
  <button class="text-white my-2 w-12">
    <%= link_to '削除', palette_second_path(palette_second), class:"bg-red-500 hover:bg-red-400 px-2 py-2 rounded", method: :delete, data: { confirm: "削除してもよろしいですか" } %>
  </button>
<% elsif current_user&.like_second?(palette_second) %>
  <button class="text-white my-2 w-12">
    <%= link_to '詳細', palette_second_path(palette_second), class:"bg-green-400 hover:bg-green-300 px-2 py-2 rounded", data: {"turbolinks" => false} %>
  </button>
  <button class="px-3 py-2">
    <%= link_to palette_second_like_second_path(palette_second_id: palette_second.id, id: palette_second.like_seconds.find{ |b| b.user_id == current_user.id }), method: :delete do %>
      <i class="fa-solid fa-heart red-heart"></i>
    <% end %>
  </button>
<% else %>
  <button class="text-white my-2 w-12">
    <%= link_to '詳細', palette_second_path(palette_second), class:"bg-green-400 hover:bg-green-300 px-2 py-2 rounded", data: {"turbolinks" => false} %>
  </button>
  <button class="px-3 py-2">
    <%= link_to palette_second_like_seconds_path(palette_second), method: :post do %>
      <i class="fa-regular fa-heart"></i>
    <% end %>
  </button>
<% end %>