config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root "palettes#new"
  get "about" => "homes#about"
  get "terms_of_use" => "homes#terms"
  get "privacy_policy" => "homes#policy"

  resources :users, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :palettes, only: [:index, :new, :create, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  resources :palette_seconds, only: [:index, :new, :create, :show, :destroy] do
    resources :like_seconds, only: [:create, :destroy]
  end

  namespace :mypage do
    resource :profile, only: [:edit, :show, :update]
    get 'palettes' => 'colors#palettes'
    get 'palette_seconds' => 'color_seconds#palette_seconds'
    get "palettes/likes" => "colors#likes"
    get "palette_seconds/likes" => "color_seconds#likes"
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  namespace :admin do
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'

    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :colors, only: [:index, :show, :edit, :update, :destroy]
    resources :color_seconds, only: [:index, :show, :edit, :update, :destroy]
  end

  post '/guest_login', to: 'user_sessions#guest_login'
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :palettes, dependent: :destroy
  has_many :palette_seconds, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likes_palettes, through: :likes, source: :palette
  has_many :like_seconds, dependent: :destroy
  has_many :like_seconds_palette_seconds, through: :like_seconds, source: :palette_second

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true, length: { maximum: 255 }

  enum role: {
    general: 0,
    admin: 1
  }

  def own?(object)
    id == object.user_id
  end

  def like(palette)
    likes_palettes << palette
  end

  def unlike(palette)
    likes_palettes.destroy(palette)
  end

  def like?(palette)
    palette.likes.pluck(:user_id).include?(id)
  end

  def like_second(palette_second)
    like_seconds_palette_seconds << palette_second
  end

  def unlike_second(palette_second)
    like_seconds_palette_seconds.destroy(palette_second)
  end

  def like_second?(palette_second)
    palette_second.like_seconds.pluck(:user_id).include?(id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  layout 'admin/layouts/admin_colorless'
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all.page(params[:page])
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = "更新に成功しました"
      redirect_to admin_user_path(@user)
    else
      flash.now[:danger] = "更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @user.destroy!
    flash[:success] = "削除に成功しました"
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :role)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  layout 'layouts/colorless'

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = '登録が完了しました'
      redirect_to root_path
    else
      flash.now[:danger] = '登録に失敗しました'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/admin/users/edit.html.erb
<div class="md:w-3/4 my-5 mx-auto">

  <div class="my-5">
    <div class="mx-auto w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
            ユーザー情報編集
        </h1>
        <%= form_with model: @user,url: admin_user_path(@user), local: true do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="my-7">
            <%= f.label :name, "名前" %>
            <%= f.text_field :name, class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', placeholder:"name@company.com" %>
          </div>
          <div class="my-7">
            <%= f.label :email, "メールアドレス" %>
            <%= f.text_field :email, class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', placeholder:"name@company.com" %>
          </div>
          <div class="my-7">
            <%= f.label :role, "権限" %>
            <%= f.select :role, User.roles.keys.map {|k| [k, k,]}, {}, class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', placeholder:"name@company.com" %>
          </div>
          <div class="my-7">
            <button class="w-full text-white bg-green-400 hover:bg-green-300  font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
              <%= f.submit '更新', class:"bg-transparent" %>
            </button>
          </div>
        <% end %>
        <%= link_to "戻る", admin_users_path %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="">
  <table class="table-auto">
    <thead>
      <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Created_at</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= l user.created_at %></td>
        <td>
          <%= link_to "詳細", admin_user_path(user) %>
          <%= link_to "編集", edit_admin_user_path(user) %>
          <%= link_to "削除", admin_user_path(user), method: :delete, data: { confirm: "削除しますか?"} %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="">
  <%= paginate @users %>
</div>

app/views/admin/users/show.html.erb
<div class="md:w-3/4 my-5 mx-auto">

  <div class="my-5">
    <div class="mx-auto w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white text-center">
          ユーザー情報
        </h1>
          <div class="my-7">
            <div class="my-2">
              登録日
            </div>
            <div>
              <%= l @user.created_at %>
            </div>
          </div>
          <div class="my-7">
            <div class="my-2">
              名前
            </div>
            <div>
              <%= @user.name %>
            </div>
          </div>
          <div class="my-7">
            <div class="my-2">
              メールアドレス
            </div>
            <div>
              <%= @user.email %>
            </div>
          </div>
          <div class="my-7">
            <div class="my-2">
              権限
            </div>
            <div>
              <%= @user.role %>
            </div>
          </div>
          <div class="my-7 flex justify-between">
            <button class="">
              <%= link_to '戻る', admin_users_path, class:" text-white bg-blue-400 hover:bg-blue-500  font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" %>
            </button>
            <button class="">
              <%= link_to '編集', edit_admin_user_path(@user), class:" text-white bg-green-400 hover:bg-green-300  font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" %>
            </button>
            <button class="">
              <%= link_to '削除', admin_user_path(@user), method: :delete, data: { confirm: "削除しますか?"}, class:" text-white bg-red-500 hover:bg-red-400  font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" %>
            </button>
          </div>
      </div>
    </div>
  </div>
</div>

<%= link_to "編集", edit_admin_user_path(@user) %>
<%= link_to "戻る", admin_users_path %>
<%= link_to "削除", admin_user_path(@user), method: :delete, data: { confirm: "削除しますか?"} %>