config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root "palettes#new"
  get "about" => "homes#about"
  get "terms_of_use" => "homes#terms"
  get "privacy_policy" => "homes#policy"

  resources :users, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :palettes, only: [:index, :new, :create, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  resources :palette_seconds, only: [:index, :new, :create, :show, :destroy] do
    resources :like_seconds, only: [:create, :destroy]
  end

  namespace :mypage do
    resource :profile, only: [:edit, :show, :update]
    get 'palettes' => 'colors#palettes'
    get 'palette_seconds' => 'color_seconds#palette_seconds'
    get "palettes/likes" => "colors#likes"
    get "palette_seconds/likes" => "color_seconds#likes"
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  namespace :admin do
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'

    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :colors, only: [:index, :show, :edit, :update, :destroy]
    resources :color_seconds, only: [:index, :show, :edit, :update, :destroy]
  end

  post '/guest_login', to: 'user_sessions#guest_login'
end

app/controllers/admin/user_sessions_controller.rb
class Admin::UserSessionsController < Admin::BaseController
  layout 'admin/layouts/admin_login'
  skip_before_action :check_admin, only: [:new, :create]
  skip_before_action :require_login, only: [:new, :create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      flash[:success] = "adminログイン成功"
      redirect_to admin_colors_path
    else
      flash.now[:danger] = "adminログイン失敗"
      render :new
    end
  end

  def destroy
    logout
    flash[:success] = "adminログアウト成功"
    redirect_to root_path
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :guest_login]
  layout 'layouts/colorless'

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      flash[:success] = "ログインしました"
      redirect_back_or_to root_path
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    logout
    flash[:success] = "ログアウトしました"
    redirect_to root_path
  end

  def guest_login
    @guest_user = User.create(
      name: 'ゲスト',
      email: SecureRandom.alphanumeric(10) + "@example.com",
      password: 'password',
      password_confirmation: 'password'
    )
    auto_login(@guest_user)
    flash[:success] = 'ゲストとしてログインしました'
    redirect_to root_path
  end
end

app/views/user_sessions/new.html.erb
<% set_meta_tags title: 'ログイン' %>
<div class="flex flex-col items-center justify-center px-2 py-8 mx-auto md:h-screen lg:py-0">
		<div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
				<div class="p-6 space-y-4 md:space-y-6 sm:p-8">
						<h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
								Sign in to your account
						</h1>
						<%= form_with url: login_path, local: true do |f| %>
								<div class="my-7">
									<%= f.label :email, "メールアドレス" %>
									<%= f.text_field :email, class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', placeholder:"name@company.com" %>
								</div>
								<div class="my-7">
									<%= f.label :password, "パスワード" %>
									<%= f.password_field :password, class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', placeholder:"••••••••" %>
								</div>
								<div class="my-7">
									<button class="w-full text-white bg-blue-400 hover:bg-blue-500  font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
										<%= f.submit 'ログイン', class:"bg-transparent" %>
									</button>
								</div>
								<div class="my-7 md:flex items-center justify-between">
									<div>
										<%= link_to 'パスワードを忘れました', new_password_reset_path, class:"text-sm font-light text-gray-500 hover:underline text-black" %>
									</div>
									<div>
										<%= link_to "新規登録はこちら", new_user_path, class:"text-sm font-light text-gray-500 hover:underline text-black" %>
									</div>
								</div>
						<% end %>
				</div>
		</div>
</div>